--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12/25/2022 11:02:25 PM
-- Server version: 8.0.31
-- Client version: 4.1
--


-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS misa_school;

CREATE DATABASE misa_school
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci;

--
-- Set default database
--
USE misa_school;

--
-- Create table `department`
--
CREATE TABLE department (
  DepartmentId char(36) DEFAULT NULL COMMENT 'ID tổ bộ môn ',
  DepartmentCode varchar(255) DEFAULT NULL COMMENT 'Mã tổ bộ môn ',
  DepartmentName varchar(100) DEFAULT NULL COMMENT 'Tên tổ bộ môn ',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày khởi tạo tổ bộ môn',
  CreatedBy varchar(100) DEFAULT NULL COMMENT 'Tổ bộ môn khởi tạo bởi',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày chỉnh sửa tổ bộ môn',
  ModifiedBy varchar(100) DEFAULT NULL COMMENT 'Tổ bộ môn chỉnh sửa bởi'
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create index `UK_departments_DepartmentId` on table `department`
--
ALTER TABLE department
ADD UNIQUE INDEX UK_departments_DepartmentId (DepartmentId);

--
-- Create table `employee`
--
CREATE TABLE employee (
  EmployeeId char(36) NOT NULL DEFAULT '' COMMENT 'ID của cán bộ ',
  EmployeeCode varchar(20) NOT NULL DEFAULT '' COMMENT 'Mã số hiệu cán bộ',
  EmployeeName varchar(100) NOT NULL DEFAULT '' COMMENT 'Tên cán bộ',
  EmployeePhone varchar(100) DEFAULT NULL COMMENT 'Số điện thoại cán bộ ',
  EmployeeEmail varchar(100) DEFAULT NULL COMMENT 'Email của cán bộ ',
  WorkingStatus tinyint DEFAULT NULL COMMENT 'Tình trạng công việc (0:nghỉ việc, 1: đang làm việc)',
  DepartmentId char(36) DEFAULT NULL,
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày khởi cán bộ',
  CreatedBy varchar(100) DEFAULT NULL COMMENT 'Cán bộ khởi tạo bởi',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày chỉnh sửa cán bộ ',
  ModifiedBy varchar(100) DEFAULT NULL COMMENT 'Cán bộ chỉnh sửa bởi',
  PRIMARY KEY (EmployeeId)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE employee
ADD CONSTRAINT FK_employees_DepartmentId FOREIGN KEY (DepartmentId)
REFERENCES department (DepartmentId);

--
-- Create table `storage`
--
CREATE TABLE storage (
  StorageId char(36) NOT NULL DEFAULT '' COMMENT 'ID của phòng kho',
  StorageCode varchar(20) DEFAULT NULL COMMENT 'Tên phòng kho ',
  StorageName varchar(100) DEFAULT NULL COMMENT 'Tên của phòng kho ',
  CreatedDate datetime DEFAULT NULL,
  CreatedBy varchar(100) DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  ModifiedBy varchar(100) DEFAULT NULL,
  PRIMARY KEY (StorageId)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `employeestorage`
--
CREATE TABLE employeestorage (
  Id char(36) NOT NULL DEFAULT '',
  EmployeeId char(36) DEFAULT NULL,
  StorageId char(36) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE employeestorage
ADD CONSTRAINT FK_employeestorage_EmployeeId FOREIGN KEY (EmployeeId)
REFERENCES employee (EmployeeId);

--
-- Create foreign key
--
ALTER TABLE employeestorage
ADD CONSTRAINT FK_employeestorage_StorageId FOREIGN KEY (StorageId)
REFERENCES storage (StorageId);

--
-- Create table `subject`
--
CREATE TABLE subject (
  SubjectId char(36) NOT NULL DEFAULT '' COMMENT 'ID môn học ',
  SubjectCode varchar(20) DEFAULT NULL COMMENT 'Mã môn  học',
  SubjectName varchar(100) DEFAULT NULL COMMENT 'Tên môn học ',
  CreatedDate datetime DEFAULT NULL,
  CreatedBy varchar(100) DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  ModifiedBy varchar(100) DEFAULT NULL,
  PRIMARY KEY (SubjectId)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `emlpoyeesubject`
--
CREATE TABLE emlpoyeesubject (
  SubjectId char(36) NOT NULL DEFAULT '' COMMENT 'ID tổ bộ môn',
  EmployeeId char(36) NOT NULL DEFAULT '' COMMENT 'ID cán bộ ',
  Id char(36) NOT NULL DEFAULT '',
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE emlpoyeesubject
ADD CONSTRAINT FK_emlpoyeesubject_EmployeeId FOREIGN KEY (EmployeeId)
REFERENCES employee (EmployeeId);

--
-- Create foreign key
--
ALTER TABLE emlpoyeesubject
ADD CONSTRAINT FK_emlpoyeesubject_SubjectId FOREIGN KEY (SubjectId)
REFERENCES subject (SubjectId);

-- 
-- Dumping data for table department
--
-- Table misa_school.department does not contain any data (it is empty)

-- 
-- Dumping data for table storage
--
-- Table misa_school.storage does not contain any data (it is empty)

-- 
-- Dumping data for table subject
--
-- Table misa_school.subject does not contain any data (it is empty)

-- 
-- Dumping data for table employee
--
-- Table misa_school.employee does not contain any data (it is empty)

-- 
-- Dumping data for table employeestorage
--
-- Table misa_school.employeestorage does not contain any data (it is empty)

-- 
-- Dumping data for table emlpoyeesubject
--
-- Table misa_school.emlpoyeesubject does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;