--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12/25/2022 10:57:24 PM
-- Server version: 8.0.31
-- Client version: 4.1
--


SET NAMES 'utf8';




